### ISSUE TITLE
Problem of training.

### ISSUE THREAD

**Issue by CLGRY** [MIC-DKFZ/MedNeXt#11]
Excuse me. When training the model, it was always suggested that the model “mednext ” was undefined, and I don't know how to modify it. What specific modification is needed? Did some of the names change?

**Comment by saikat-roy** [comment]
Hi @CLGRY. Could you share the command you ran and the error log?

**Comment by CLGRY** [comment]
> Hi @CLGRY. Could you share the command you ran and the error log?

OK, thanks very much. The command and the error log are as follows.

command:
mednextv1_plan_and_preprocess -t 121 -pl3d ExperimentPlanner3D_v21_customTargetSpacing_1x1x1 -pl2d ExperimentPlanner2D_v21_customTargetSpacing_1x1x1

error log:
Traceback (most recent call last):
File "/home/chenruiyue/anaconda3/envs/mednext/bin/mednextv1_plan_and_preprocess", line 5, in
from nnunet_mednext.experiment_planning.nnUNet_plan_and_preprocess import main
ModuleNotFoundError: No module named 'nnunet_mednext'

**Comment by saikat-roy** [comment]
Could you try changing your working directory to wherever you downloaded the repo and run it again? Something like:

```
cd ~/MedNeXt
mednextv1_plan_and_preprocess -t 121 -pl3d ExperimentPlanner3D_v21_customTargetSpacing_1x1x1 -pl2d ExperimentPlanner2D_v21_customTargetSpacing_1x1x1
```

**Comment by CLGRY** [comment]
> Could you try changing your working directory to wherever you downloaded the repo and run it again? Something like:
> 
> ```
> cd ~/MedNeXt
> mednextv1_plan_and_preprocess -t 121 -pl3d ExperimentPlanner3D_v21_customTargetSpacing_1x1x1 -pl2d ExperimentPlanner2D_v21_customTargetSpacing_1x1x1
> ```

Yes, have entered. The imformation in Vscode is as follows:

(mednext) :~/Projs/mednext$ ls
build  DATASET  documentation  LICENSE  mednextv1.egg-info  nnunet_mednext  README.md  setup.cfg  setup.py  tests
(mednext) chenruiyue@xinlab:~/Projs/mednext$ mednextv1_plan_and_preprocess -t 121 -pl3d ExperimentPlanner3D_v21_customTargetSpacing_1x1x1 -pl2d ExperimentPlanner2D_v21_customTargetSpacing_1x1x1
Traceback (most recent call last):
  File "/home/chenruiyue/anaconda3/envs/mednext/bin/mednextv1_plan_and_preprocess", line 5, in <module>
    from nnunet_mednext.experiment_planning.nnUNet_plan_and_preprocess import main
ModuleNotFoundError: No module named 'nnunet_mednext'

**Comment by CLGRY** [comment]
> Could you try changing your working directory to wherever you downloaded the repo and run it again? Something like:
> 
> ```
> cd ~/MedNeXt
> mednextv1_plan_and_preprocess -t 121 -pl3d ExperimentPlanner3D_v21_customTargetSpacing_1x1x1 -pl2d ExperimentPlanner2D_v21_customTargetSpacing_1x1x1
> ```

Yes, have entered. The imformation in Vscode is as follows:

(mednext) chenruiyue@xinlab:~/Projs/mednext$ ls
build  DATASET  documentation  LICENSE  mednextv1.egg-info  nnunet_mednext  README.md  setup.cfg  setup.py  tests
(mednext) chenruiyue@xinlab:~/Projs/mednext$ mednextv1_plan_and_preprocess -t 121 -pl3d ExperimentPlanner3D_v21_customTargetSpacing_1x1x1 -pl2d ExperimentPlanner2D_v21_customTargetSpacing_1x1x1
Traceback (most recent call last):
  File "/home/chenruiyue/anaconda3/envs/mednext/bin/mednextv1_plan_and_preprocess", line 5, in <module>
    from nnunet_mednext.experiment_planning.nnUNet_plan_and_preprocess import main
ModuleNotFoundError: No module named 'nnunet_mednext'
(mednext) chenruiyue@xinlab:~/Projs/mednext$

**Comment by CLGRY** [comment]
> Could you try changing your working directory to wherever you downloaded the repo and run it again? Something like:
> 
> ```
> cd ~/MedNeXt
> mednextv1_plan_and_preprocess -t 121 -pl3d ExperimentPlanner3D_v21_customTargetSpacing_1x1x1 -pl2d ExperimentPlanner2D_v21_customTargetSpacing_1x1x1
> ```

Yes, have entered. The imformation in Vscode is as follows:

(mednext) :~/Projs/mednext$ ls
build  DATASET  documentation  LICENSE  mednextv1.egg-info  nnunet_mednext  README.md  setup.cfg  setup.py  tests
(mednext) :~/Projs/mednext$ mednextv1_plan_and_preprocess -t 121 -pl3d ExperimentPlanner3D_v21_customTargetSpacing_1x1x1 -pl2d ExperimentPlanner2D_v21_customTargetSpacing_1x1x1
Traceback (most recent call last):
  File "/home/chenruiyue/anaconda3/envs/mednext/bin/mednextv1_plan_and_preprocess", line 5, in <module>
    from nnunet_mednext.experiment_planning.nnUNet_plan_and_preprocess import main
ModuleNotFoundError: No module named 'nnunet_mednext'
(mednext) :~/Projs/mednext$

**Comment by CLGRY** [comment]
> Could you try changing your working directory to wherever you downloaded the repo and run it again? Something like:
> 
> ```
> cd ~/MedNeXt
> mednextv1_plan_and_preprocess -t 121 -pl3d ExperimentPlanner3D_v21_customTargetSpacing_1x1x1 -pl2d ExperimentPlanner2D_v21_customTargetSpacing_1x1x1
> ```

Yes, have entered. The imformation in Vscode is as follows:

(mednext) :/Projs/mednext$ ls
build DATASET documentation LICENSE mednextv1.egg-info nnunet_mednext README.md setup.cfg setup.py tests
(mednext) :/Projs/mednext$ mednextv1_plan_and_preprocess -t 121 -pl3d ExperimentPlanner3D_v21_customTargetSpacing_1x1x1 -pl2d ExperimentPlanner2D_v21_customTargetSpacing_1x1x1
Traceback (most recent call last):
File "/home/anaconda3/envs/mednext/bin/mednextv1_plan_and_preprocess", line 5, in
from nnunet_mednext.experiment_planning.nnUNet_plan_and_preprocess import main
ModuleNotFoundError: No module named 'nnunet_mednext'
(mednext) :~/Projs/mednext$

**Comment by CLGRY** [comment]
> Could you try changing your working directory to wherever you downloaded the repo and run it again? Something like:
> 
> ```
> cd ~/MedNeXt
> mednextv1_plan_and_preprocess -t 121 -pl3d ExperimentPlanner3D_v21_customTargetSpacing_1x1x1 -pl2d ExperimentPlanner2D_v21_customTargetSpacing_1x1x1
> ```

The error location is:

#!/home/anaconda3/envs/mednext/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from nnunet_mednext.experiment_planning.nnUNet_plan_and_preprocess import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())

**Comment by saikat-roy** [comment]
Seemingly your python can't locate the installed package. Could you try the following from the downloaded package folder? It should bypass all installation issues and get the package running atleast

`python mednext_nnunet/experiment_planning/nnUNet_plan_and_preprocess.py -t 121 -pl3d ExperimentPlanner3D_v21_customTargetSpacing_1x1x1 -pl2d ExperimentPlanner2D_v21_customTargetSpacing_1x1x1
`

**Comment by CLGRY** [comment]
> Seemingly your python can't locate the installed package. Could you try the following from the downloaded package folder? It should bypass all installation issues and get the package running atleast
> 
> `python mednext_nnunet/experiment_planning/nnUNet_plan_and_preprocess.py -t 121 -pl3d ExperimentPlanner3D_v21_customTargetSpacing_1x1x1 -pl2d ExperimentPlanner2D_v21_customTargetSpacing_1x1x1 `

Can't solve the problem, others are having the same problem.

**Comment by saikat-roy** [comment]
Okay so, I was able to recreate the issue after I uninstalled my local copy of the package.

The package works fine if installed in editable mode. Please uninstall existing copies of the package and try installing it with the commands below.
```
cd <your_path>/MedNeXt
pip install -e .
```

For some reason, a standard install does not work and I will have to explore later why this is the case. 

Please try this @CLGRY and see if it fixes your issues.

**Comment by CLGRY** [comment]
OK,thanks.
Now the problem is that:

RuntimeError: Could not find a task with the ID 139. Make sure the requested task ID exists and that nnU-Net knows where raw and preprocessed data are located (see Documentation - Installation). Here are your currently defined folders:
nnUNet_preprocessed=/home/chenruiyue/Projs/mednext/DATASET/nnUNet_preprocessed
RESULTS_FOLDER=/home/chenruiyue/Projs/mednext/DATASET/nnUNet_trained_models
nnUNet_raw_data_base=/home/chenruiyue/Projs/mednext/DATASET/nnUNet_raw_data_base/nnUNet_raw_data/Dataset139_mednext
If something is not right, adapt your environemnt variables.

And my environemnt variables is that:
export nnUNet_raw_data_base="/home/Projs/mednext/DATASET/nnUNet_raw_data_base/nnUNet_raw_data/Dataset139_mednext"
export nnUNet_preprocessed="/home/Projs/mednext/DATASET/nnUNet_preprocessed"
export RESULTS_FOLDER="/home/Projs/mednext/DATASET/nnUNet_trained_models"

My taskID is 139. （I also tried many other IDs）

My file structure is as follows：
![image](https://github.com/MIC-DKFZ/MedNeXt/assets/85401636/e21eb7bd-84ce-4ddd-bb58-4075e7f22e58)

Thanks for your reply.

**Comment by CLGRY** [comment]
> Okay so, I was able to recreate the issue after I uninstalled my local copy of the package.
> 
> The package works fine if installed in editable mode. Please uninstall existing copies of the package and try installing it with the commands below.
> 
> ```
> cd <your_path>/MedNeXt
> pip install -e .
> ```
> 
> For some reason, a standard install does not work and I will have to explore later why this is the case.
> 
> Please try this @CLGRY and see if it fixes your issues.

OK,thanks.
Now the problem is that:

RuntimeError: Could not find a task with the ID 139. Make sure the requested task ID exists and that nnU-Net knows where raw and preprocessed data are located (see Documentation - Installation). Here are your currently defined folders:
nnUNet_preprocessed=/home/chenruiyue/Projs/mednext/DATASET/nnUNet_preprocessed
RESULTS_FOLDER=/home/chenruiyue/Projs/mednext/DATASET/nnUNet_trained_models
nnUNet_raw_data_base=/home/chenruiyue/Projs/mednext/DATASET/nnUNet_raw_data_base/nnUNet_raw_data/Dataset139_mednext
If something is not right, adapt your environemnt variables.

And my environemnt variables is that:
export nnUNet_raw_data_base="/home/Projs/mednext/DATASET/nnUNet_raw_data_base/nnUNet_raw_data/Dataset139_mednext"
export nnUNet_preprocessed="/home/Projs/mednext/DATASET/nnUNet_preprocessed"
export RESULTS_FOLDER="/home/Projs/mednext/DATASET/nnUNet_trained_models"

My taskID is 139. （I also tried many other IDs）

My file structure is as follows：
image

Thanks for your reply.

**Comment by CLGRY** [comment]
> Okay so, I was able to recreate the issue after I uninstalled my local copy of the package.
> 
> The package works fine if installed in editable mode. Please uninstall existing copies of the package and try installing it with the commands below.
> 
> ```
> cd <your_path>/MedNeXt
> pip install -e .
> ```
> 
> For some reason, a standard install does not work and I will have to explore later why this is the case.
> 
> Please try this @CLGRY and see if it fixes your issues.

OK,thanks.
Now the problem is that:

RuntimeError: Could not find a task with the ID 139. Make sure the requested task ID exists and that nnU-Net knows where raw and preprocessed data are located (see Documentation - Installation). Here are your currently defined folders:
nnUNet_preprocessed=/home/Projs/mednext/DATASET/nnUNet_preprocessed
RESULTS_FOLDER=/home/Projs/mednext/DATASET/nnUNet_trained_models
nnUNet_raw_data_base=/home/Projs/mednext/DATASET/nnUNet_raw_data_base/nnUNet_raw_data/Dataset139_mednext
If something is not right, adapt your environemnt variables.

And my environemnt variables is that:
export nnUNet_raw_data_base="/home/Projs/mednext/DATASET/nnUNet_raw_data_base/nnUNet_raw_data/Dataset139_mednext"
export nnUNet_preprocessed="/home/Projs/mednext/DATASET/nnUNet_preprocessed"
export RESULTS_FOLDER="/home/Projs/mednext/DATASET/nnUNet_trained_models"

My taskID is 139. （I also tried many other IDs）

My file structure is as follows：
![image](https://github.com/MIC-DKFZ/MedNeXt/assets/85401636/448e07ed-80c3-4d03-91b0-9b59e46dfaa9)


Thanks for your reply.

**Comment by CLGRY** [comment]
> Okay so, I was able to recreate the issue after I uninstalled my local copy of the package.
> 
> The package works fine if installed in editable mode. Please uninstall existing copies of the package and try installing it with the commands below.
> 
> ```
> cd <your_path>/MedNeXt
> pip install -e .
> ```
> 
> For some reason, a standard install does not work and I will have to explore later why this is the case.
> 
> Please try this @CLGRY and see if it fixes your issues.

OK,thanks.
Now the problem is that:

Traceback (most recent call last):
  File "/home/anaconda3/envs/mednext/bin/mednextv1_plan_and_preprocess", line 33, in <module>
    sys.exit(load_entry_point('mednextv1', 'console_scripts', 'mednextv1_plan_and_preprocess')())
  File "/home/Projs/mednext/nnunet_mednext/experiment_planning/nnUNet_plan_and_preprocess.py", line 107, in main
    crop(task_name, False, tf)
  File "/home/Projs/mednext/nnunet_mednext/experiment_planning/utils.py", line 131, in crop
    lists, _ = create_lists_from_splitted_dataset(splitted_4d_output_dir_task)
  File "/home/Projs/mednext/nnunet_mednext/experiment_planning/utils.py", line 88, in create_lists_from_splitted_dataset
    training_files = d['training']
KeyError: 'training'

And my environemnt variables is that:
export export nnUNet_raw_data_base="/home/Projs/mednext/DATASET/nnUNet_raw_data_base"
export nnUNet_preprocessed="/home/Projs/mednext/DATASET/nnUNet_preprocessed"
export RESULTS_FOLDER="/home/Projs/mednext/DATASET/nnUNet_trained_models"

My taskID is 139. 

My file structure is as follows：
![image](https://github.com/MIC-DKFZ/MedNeXt/assets/85401636/5a91e65d-7fde-45b0-89d5-c407c9957f9f)


Thanks for your reply.

**Comment by saikat-roy** [comment]
It seems like it can't read the `training` key from your `dataset.json`. Please verify that you performed dataset conversion and generated a json file following [this](https://github.com/MIC-DKFZ/nnUNet/blob/nnunetv1/documentation/dataset_conversion.md) guide from nnUNet (v1).

**Comment by CLGRY** [comment]
> It seems like it can't read the `training` key from your `dataset.json`. Please verify that you performed dataset conversion and generated a json file following [this](https://github.com/MIC-DKFZ/nnUNet/blob/nnunetv1/documentation/dataset_conversion.md) guide from nnUNet (v1).

OK！
After I modified dataset.json, I ran "mednextv1_plan_and_preprocess -t 770 -pl3d ExperimentPlanner3D_v21_customTargetSpacing_1x1x1 -pl2d ExperimentPlanner2D_v21_customTargetSpacing_1x1x1". The cropped data can be generated at the location shown below, but no results are generated in nnUNet_preprocessed.

![image](https://github.com/MIC-DKFZ/MedNeXt/assets/85401636/6a049d0d-f9db-4bd9-a1a2-9f3528b6333f)



![image](https://github.com/MIC-DKFZ/MedNeXt/assets/85401636/008a1029-25d3-4b9b-96e8-7c3be21d7d16)


And the error message is as follows：
Feta_0001
Feta_0002
Feta_0003
Feta_0004
Feta_0005
Feta_0006
Feta_0013
Feta_0007
Feta_0014
Feta_0015
Feta_0008
Feta_0010
Feta_0009
Feta_0011
Feta_0012
Feta_0016
Feta_0017
Feta_0018
Feta_0019
Feta_0020
Feta_0029
Feta_0026
Feta_0021
Feta_0030
Feta_0031
Feta_0027
Feta_0028
Feta_0032
Feta_0033
Feta_0034
Feta_0023
Feta_0024
Feta_0025
Feta_0041
Feta_0044
Feta_0038
Feta_0045
Feta_0042
Feta_0046
Feta_0043
Feta_0039
Feta_0047
Feta_0040
Feta_0035
Feta_0048
Feta_0050
Feta_0049
Feta_0051
Feta_0052
Feta_0056
Feta_0036
Feta_0057
Feta_0059
Feta_0053
Feta_0058
Feta_0062
Feta_0037
Feta_0060
Feta_0063
Feta_0061
Feta_0064
Feta_0054
Feta_0065
Feta_0055
Feta_0066
Feta_0067
Feta_0068
Feta_0071
Feta_0069
Feta_0072
Feta_0070
Feta_0074
Feta_0073
Feta_0075
Feta_0076
Feta_0077
Feta_0080
Feta_0078
Feta_0079
Traceback (most recent call last):
  File "/home/anaconda3/envs/mednext/bin/mednextv1_plan_and_preprocess", line 33, in <module>
    sys.exit(load_entry_point('mednextv1', 'console_scripts', 'mednextv1_plan_and_preprocess')())
  File "/home/Projs/mednext/nnunet_mednext/experiment_planning/nnUNet_plan_and_preprocess.py", line 114, in main
    planner_3d = recursive_find_python_class([search_in], planner_name3d, current_module="nnunet.experiment_planning")
  File "/home/Projs/mednext/nnunet_mednext/training/model_restore.py", line 28, in recursive_find_python_class
    m = importlib.import_module(current_module + "." + modname)
  File "/home/anaconda3/envs/mednext/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked


so hard...

**Comment by saikat-roy** [comment]
I see that you have closed this issue @CLGRY. Hopefully you managed to fix it yourself. 

Still I had a follow up comment that I wanted to make. I think your second problem was a case of the preprocesor class not being found. My base nnUNet installation somehow interfered and I couldn't see this issue. I will try to patch it tomorrow.
