### ISSUE TITLE
about batch_size

### ISSUE THREAD

**Issue by CLGRY** [MIC-DKFZ/MedNeXt#12]
hi , i want to set the batch_size to 2, as it is out of memory, do you know where to set? 

![image](https://github.com/MIC-DKFZ/MedNeXt/assets/85401636/e9218c29-1459-445f-865b-261f9e3e7d47)

**Comment by saikat-roy** [comment]
There are different places to set the batch size. You could open the plans file in Python as in [here](https://github.com/MIC-DKFZ/nnUNet/blob/nnunetv1/documentation/tutorials/edit_plans_files.md) and change it or you could add it to the constructor of any trainer in `./nnunet_mednext/training/network_training/MedNeXt/nnUNetTrainerV2_MedNeXt.py` like so

```
def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.batch_size = 2
```

**Comment by CLGRY** [comment]
> There are different places to set the batch size. You could open the plans file in Python as in [here](https://github.com/MIC-DKFZ/nnUNet/blob/nnunetv1/documentation/tutorials/edit_plans_files.md) and change it or you could add it to the constructor of any trainer in `./nnunet_mednext/training/network_training/MedNeXt/nnUNetTrainerV2_MedNeXt.py` like so
> 
> ```
> def __init__(self, *args, **kwargs):
>     super().__init__(*args, **kwargs)
>     self.batch_size = 2
> ```

May I ask you where the batch_size of this project can be changed, or what are the command line parameters, which can not be found at all.
