### ISSUE TITLE
replace nnunetv2's with MedNeXt v1 have some problems

### ISSUE THREAD

**Issue by yml-bit** [MIC-DKFZ/MedNeXt#13]
Hi, I replaced the model in nnunetv2 with MedNeXt v1 and trained the conveyor farmer i function as a nan value, and I see that the original nnunetv2 raw output is 3
convolution, and after adding a 3d convolution to the deep supervised output of MedNeXt v1, the situation is not improved!

**Comment by saikat-roy** [comment]
Hey I'm sorry for the late reply. Did you manage to solve your issue?
