### ISSUE TITLE
Sharing the precise setup for your experiments

### ISSUE THREAD

**Issue by Zhack47** [MIC-DKFZ/MedNeXt#14]
Hello @saikat-roy, thank you for open sourcing this work!

I am currently trying to reproduce it on my side, however, using the same conditions as in your supplementary material (i.e.: batch size= 2, patch 128x128x128 and 250 it/epochs wit the Small (S) model and k5 kernel, i get a 200 sec/ epoch runtime, different from your 117 secs.

I have eliminated the other options, so I am now left with setup differences.
Could you give us the setup you used ( GPU, pytorch version..) to train your model ?

Regards

Zach

**Comment by saikat-roy** [comment]
Hey @Zhack47. My first thought is that maybe I used a Tesla A100 40GB for baselining the S model _without_  any checkpointing, and that your GPU is different. If that doesn't help, I can share my remaining setup.
