### ISSUE TITLE
Very slow training speed for nnUNetTrainerV2_MedNeXt_L_kernel3

### ISSUE THREAD

**Issue by Itsanewday** [MIC-DKFZ/MedNeXt#20]
Hi, I try to train a nnUNetTrainerV2_MedNeXt_L_kernel3 and find that it is much slower than the basic nnUNet.  When i train the model on 3090, the basic ResencUNet takes about 150 seconds, however this trainer takes more than 20 minutes. How can i speed up?

**Comment by saikat-roy** [comment]
Well the difference between the ResencUNet and MedNeXt is the heavy amount of checkpointing it uses. If you reduce the checkpointing, you would quickly run out of VRAM. Though 20 minutes does seem very high. 

The basic suggestions that I could give you is using a smaller configuration like M or B. In my experience, they aren't necessary too bad from the L variant.
